export interface Airport {
  iata: string;
  name: string;
  city: string;
  country: string;
  lat?: number;
  lon?: number;
}

export const AIRPORTS: Airport[] = [
  // US
  { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "US", lat: 40.6413, lon: -73.7781 },
  { iata: "LGA", name: "LaGuardia", city: "New York", country: "US", lat: 40.7772, lon: -73.8726 },
  { iata: "EWR", name: "Newark Liberty International", city: "New York", country: "US", lat: 40.6895, lon: -74.1745 },
  { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "US", lat: 33.9425, lon: -118.4081 },
  { iata: "BUR", name: "Hollywood Burbank", city: "Burbank", country: "US", lat: 34.2007, lon: -118.3585 },
  { iata: "LGB", name: "Long Beach", city: "Long Beach", country: "US", lat: 33.8177, lon: -118.1516 },
  { iata: "SNA", name: "John Wayne Airport", city: "Santa Ana", country: "US", lat: 33.6757, lon: -117.8676 },
  { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "US", lat: 41.9742, lon: -87.9073 },
  { iata: "MDW", name: "Midway International", city: "Chicago", country: "US", lat: 41.7868, lon: -87.7522 },
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta", city: "Atlanta", country: "US" },
  { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "US", lat: 32.8998, lon: -97.0403 },
  { iata: "DAL", name: "Dallas Love Field", city: "Dallas", country: "US", lat: 32.8471, lon: -96.8517 },
  { iata: "DEN", name: "Denver International", city: "Denver", country: "US" },
  { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "US", lat: 37.6213, lon: -122.3790 },
  { iata: "OAK", name: "Oakland International", city: "Oakland", country: "US", lat: 37.7213, lon: -122.2208 },
  { iata: "SJC", name: "Norman Y. Mineta San Jose", city: "San Jose", country: "US", lat: 37.3626, lon: -121.9290 },
  { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "US" },
  { iata: "MIA", name: "Miami International", city: "Miami", country: "US", lat: 25.7959, lon: -80.2870 },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood International", city: "Fort Lauderdale", country: "US", lat: 26.0726, lon: -80.1527 },
  { iata: "PBI", name: "Palm Beach International", city: "West Palm Beach", country: "US", lat: 26.6832, lon: -80.0956 },
  { iata: "BOS", name: "Logan International", city: "Boston", country: "US", lat: 42.3656, lon: -71.0096 },
  { iata: "MCO", name: "Orlando International", city: "Orlando", country: "US" },
  { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "US" },
  { iata: "PHX", name: "Phoenix Sky Harbor", city: "Phoenix", country: "US" },
  { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "US" },
  { iata: "HOU", name: "William P. Hobby", city: "Houston", country: "US" },
  { iata: "MSP", name: "Minneapolis-St. Paul International", city: "Minneapolis", country: "US" },
  { iata: "DTW", name: "Detroit Metropolitan", city: "Detroit", country: "US" },
  { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "US" },
  { iata: "CLT", name: "Charlotte Douglas International", city: "Charlotte", country: "US" },
  { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "US", lat: 39.1754, lon: -76.6683 },
  { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington", country: "US", lat: 38.8512, lon: -77.0402 },
  { iata: "IAD", name: "Dulles International", city: "Washington", country: "US", lat: 38.9531, lon: -77.4565 },
  { iata: "SAN", name: "San Diego International", city: "San Diego", country: "US" },
  { iata: "TPA", name: "Tampa International", city: "Tampa", country: "US" },
  { iata: "PDX", name: "Portland International", city: "Portland", country: "US" },
  { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "US" },
  { iata: "AUS", name: "Austin-Bergstrom International", city: "Austin", country: "US" },
  { iata: "BNA", name: "Nashville International", city: "Nashville", country: "US" },
  { iata: "MCI", name: "Kansas City International", city: "Kansas City", country: "US" },
  { iata: "STL", name: "St. Louis Lambert International", city: "St. Louis", country: "US" },
  { iata: "RDU", name: "Raleigh-Durham International", city: "Raleigh", country: "US" },
  { iata: "MEM", name: "Memphis International", city: "Memphis", country: "US" },
  { iata: "IND", name: "Indianapolis International", city: "Indianapolis", country: "US" },
  { iata: "CMH", name: "John Glenn Columbus International", city: "Columbus", country: "US" },
  { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "US" },
  { iata: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", country: "US" },
  { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "US" },
  { iata: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage", country: "US" },
  { iata: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", country: "US" },
  { iata: "CLE", name: "Cleveland Hopkins International", city: "Cleveland", country: "US" },
  { iata: "CVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", country: "US" },
  { iata: "SAT", name: "San Antonio International", city: "San Antonio", country: "US" },
  { iata: "JAX", name: "Jacksonville International", city: "Jacksonville", country: "US" },
  { iata: "SMF", name: "Sacramento International", city: "Sacramento", country: "US" },
  { iata: "RSW", name: "Southwest Florida International", city: "Fort Myers", country: "US" },
  { iata: "ABQ", name: "Albuquerque International Sunport", city: "Albuquerque", country: "US" },
  { iata: "TUS", name: "Tucson International", city: "Tucson", country: "US" },
  { iata: "OKC", name: "Will Rogers World", city: "Oklahoma City", country: "US" },
  { iata: "OMA", name: "Eppley Airfield", city: "Omaha", country: "US" },
  { iata: "BOI", name: "Boise Airport", city: "Boise", country: "US" },
  { iata: "CHS", name: "Charleston International", city: "Charleston", country: "US" },
  { iata: "SAV", name: "Savannah/Hilton Head International", city: "Savannah", country: "US" },
  { iata: "RIC", name: "Richmond International", city: "Richmond", country: "US" },
  { iata: "BUF", name: "Buffalo Niagara International", city: "Buffalo", country: "US" },
  { iata: "ROC", name: "Frederick Douglass Greater Rochester International", city: "Rochester", country: "US" },
  { iata: "ALB", name: "Albany International", city: "Albany", country: "US" },
  { iata: "BDL", name: "Bradley International", city: "Hartford", country: "US" },
  { iata: "PVD", name: "Rhode Island T. F. Green International", city: "Providence", country: "US" },
  { iata: "PWM", name: "Portland International Jetport", city: "Portland", country: "US" },
  { iata: "ORF", name: "Norfolk International", city: "Norfolk", country: "US" },
  { iata: "TUL", name: "Tulsa International", city: "Tulsa", country: "US" },
  { iata: "LIT", name: "Bill and Hillary Clinton National", city: "Little Rock", country: "US" },
  { iata: "GRR", name: "Gerald R. Ford International", city: "Grand Rapids", country: "US" },
  { iata: "SDF", name: "Louisville Muhammad Ali International", city: "Louisville", country: "US" },
  { iata: "TYS", name: "McGhee Tyson", city: "Knoxville", country: "US" },
  { iata: "GSP", name: "Greenville-Spartanburg International", city: "Greenville", country: "US" },
  { iata: "BHM", name: "Birmingham-Shuttlesworth International", city: "Birmingham", country: "US" },
  { iata: "DSM", name: "Des Moines International", city: "Des Moines", country: "US" },
  { iata: "FAT", name: "Fresno Yosemite International", city: "Fresno", country: "US" },
  { iata: "GEG", name: "Spokane International", city: "Spokane", country: "US" },

  // UK / Europe
  { iata: "LHR", name: "Heathrow", city: "London", country: "GB" },
  { iata: "LGW", name: "Gatwick", city: "London", country: "GB" },
  { iata: "STN", name: "Stansted", city: "London", country: "GB" },
  { iata: "LCY", name: "London City", city: "London", country: "GB" },
  { iata: "MAN", name: "Manchester", city: "Manchester", country: "GB" },
  { iata: "EDI", name: "Edinburgh", city: "Edinburgh", country: "GB" },
  { iata: "GLA", name: "Glasgow International", city: "Glasgow", country: "GB" },
  { iata: "CDG", name: "Charles de Gaulle", city: "Paris", country: "FR" },
  { iata: "ORY", name: "Orly", city: "Paris", country: "FR" },
  { iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "NL" },
  { iata: "FRA", name: "Frankfurt", city: "Frankfurt", country: "DE" },
  { iata: "MUC", name: "Munich", city: "Munich", country: "DE" },
  { iata: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "DE" },
  { iata: "MAD", name: "Adolfo Suarez Barajas", city: "Madrid", country: "ES" },
  { iata: "BCN", name: "El Prat", city: "Barcelona", country: "ES" },
  { iata: "FCO", name: "Leonardo da Vinci-Fiumicino", city: "Rome", country: "IT" },
  { iata: "MXP", name: "Malpensa", city: "Milan", country: "IT" },
  { iata: "LIN", name: "Linate", city: "Milan", country: "IT" },
  { iata: "ZRH", name: "Zurich", city: "Zurich", country: "CH" },
  { iata: "GVA", name: "Geneva", city: "Geneva", country: "CH" },
  { iata: "VIE", name: "Vienna International", city: "Vienna", country: "AT" },
  { iata: "BRU", name: "Brussels", city: "Brussels", country: "BE" },
  { iata: "CPH", name: "Copenhagen", city: "Copenhagen", country: "DK" },
  { iata: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "NO" },
  { iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "SE" },
  { iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "FI" },
  { iata: "LIS", name: "Lisbon Humberto Delgado", city: "Lisbon", country: "PT" },
  { iata: "OPO", name: "Francisco de Sa Carneiro", city: "Porto", country: "PT" },
  { iata: "ATH", name: "Athens International", city: "Athens", country: "GR" },
  { iata: "WAW", name: "Chopin International", city: "Warsaw", country: "PL" },
  { iata: "PRG", name: "Vaclav Havel", city: "Prague", country: "CZ" },
  { iata: "BUD", name: "Budapest Ferenc Liszt", city: "Budapest", country: "HU" },
  { iata: "SVO", name: "Sheremetyevo International", city: "Moscow", country: "RU" },
  { iata: "IST", name: "Istanbul", city: "Istanbul", country: "TR" },
  { iata: "SAW", name: "Sabiha Gokcen", city: "Istanbul", country: "TR" },
  { iata: "DUB", name: "Dublin", city: "Dublin", country: "IE" },
  { iata: "NCE", name: "Nice Cote d'Azur", city: "Nice", country: "FR" },
  { iata: "LYS", name: "Lyon-Saint Exupery", city: "Lyon", country: "FR" },
  { iata: "DUS", name: "Dusseldorf", city: "Dusseldorf", country: "DE" },
  { iata: "HAM", name: "Hamburg", city: "Hamburg", country: "DE" },
  { iata: "STR", name: "Stuttgart", city: "Stuttgart", country: "DE" },
  { iata: "CGN", name: "Cologne Bonn", city: "Cologne", country: "DE" },
  { iata: "AGP", name: "Malaga-Costa del Sol", city: "Malaga", country: "ES" },
  { iata: "PMI", name: "Palma de Mallorca", city: "Palma de Mallorca", country: "ES" },
  { iata: "VLC", name: "Valencia", city: "Valencia", country: "ES" },
  { iata: "NAP", name: "Naples International", city: "Naples", country: "IT" },
  { iata: "VCE", name: "Marco Polo", city: "Venice", country: "IT" },
  { iata: "BLQ", name: "Bologna Guglielmo Marconi", city: "Bologna", country: "IT" },
  { iata: "KEF", name: "Keflavik International", city: "Reykjavik", country: "IS" },
  { iata: "RIX", name: "Riga International", city: "Riga", country: "LV" },
  { iata: "TLL", name: "Tallinn", city: "Tallinn", country: "EE" },
  { iata: "VNO", name: "Vilnius", city: "Vilnius", country: "LT" },
  { iata: "KRK", name: "John Paul II Krakow-Balice", city: "Krakow", country: "PL" },
  { iata: "OTP", name: "Henri Coanda International", city: "Bucharest", country: "RO" },
  { iata: "SOF", name: "Sofia", city: "Sofia", country: "BG" },
  { iata: "BEG", name: "Belgrade Nikola Tesla", city: "Belgrade", country: "RS" },
  { iata: "ZAG", name: "Zagreb", city: "Zagreb", country: "HR" },
  { iata: "DBV", name: "Dubrovnik", city: "Dubrovnik", country: "HR" },
  { iata: "MLA", name: "Malta International", city: "Malta", country: "MT" },
  { iata: "LCA", name: "Larnaca International", city: "Larnaca", country: "CY" },

  // Middle East
  { iata: "DXB", name: "Dubai International", city: "Dubai", country: "AE" },
  { iata: "AUH", name: "Abu Dhabi International", city: "Abu Dhabi", country: "AE" },
  { iata: "DOH", name: "Hamad International", city: "Doha", country: "QA" },
  { iata: "RUH", name: "King Khalid International", city: "Riyadh", country: "SA" },
  { iata: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "SA" },
  { iata: "KWI", name: "Kuwait International", city: "Kuwait City", country: "KW" },
  { iata: "BAH", name: "Bahrain International", city: "Manama", country: "BH" },
  { iata: "MCT", name: "Muscat International", city: "Muscat", country: "OM" },
  { iata: "TLV", name: "Ben Gurion International", city: "Tel Aviv", country: "IL" },
  { iata: "AMM", name: "Queen Alia International", city: "Amman", country: "JO" },
  { iata: "BEY", name: "Rafic Hariri International", city: "Beirut", country: "LB" },
  { iata: "DMM", name: "King Fahd International", city: "Dammam", country: "SA" },
  { iata: "MED", name: "Prince Mohammad bin Abdulaziz International", city: "Medina", country: "SA" },
  { iata: "SHJ", name: "Sharjah International", city: "Sharjah", country: "AE" },
  { iata: "IKA", name: "Imam Khomeini International", city: "Tehran", country: "IR" },

  // Asia-Pacific
  { iata: "NRT", name: "Narita International", city: "Tokyo", country: "JP" },
  { iata: "HND", name: "Haneda", city: "Tokyo", country: "JP" },
  { iata: "KIX", name: "Kansai International", city: "Osaka", country: "JP" },
  { iata: "ICN", name: "Incheon International", city: "Seoul", country: "KR" },
  { iata: "PEK", name: "Beijing Capital International", city: "Beijing", country: "CN" },
  { iata: "PKX", name: "Beijing Daxing International", city: "Beijing", country: "CN" },
  { iata: "PVG", name: "Pudong International", city: "Shanghai", country: "CN" },
  { iata: "SHA", name: "Hongqiao International", city: "Shanghai", country: "CN" },
  { iata: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "HK" },
  { iata: "SIN", name: "Changi", city: "Singapore", country: "SG" },
  { iata: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "TH" },
  { iata: "DMK", name: "Don Mueang", city: "Bangkok", country: "TH" },
  { iata: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "MY" },
  { iata: "CGK", name: "Soekarno-Hatta International", city: "Jakarta", country: "ID" },
  { iata: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "PH" },
  { iata: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "VN" },
  { iata: "HAN", name: "Noi Bai International", city: "Hanoi", country: "VN" },
  { iata: "DEL", name: "Indira Gandhi International", city: "Delhi", country: "IN" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj", city: "Mumbai", country: "IN" },
  { iata: "BLR", name: "Kempegowda International", city: "Bengaluru", country: "IN" },
  { iata: "MAA", name: "Chennai International", city: "Chennai", country: "IN" },
  { iata: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "IN" },
  { iata: "COK", name: "Cochin International", city: "Kochi", country: "IN" },
  { iata: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "AU" },
  { iata: "MEL", name: "Melbourne", city: "Melbourne", country: "AU" },
  { iata: "BNE", name: "Brisbane", city: "Brisbane", country: "AU" },
  { iata: "PER", name: "Perth", city: "Perth", country: "AU" },
  { iata: "AKL", name: "Auckland", city: "Auckland", country: "NZ" },
  { iata: "NGO", name: "Chubu Centrair International", city: "Nagoya", country: "JP" },
  { iata: "FUK", name: "Fukuoka", city: "Fukuoka", country: "JP" },
  { iata: "CTS", name: "New Chitose", city: "Sapporo", country: "JP" },
  { iata: "PUS", name: "Gimhae International", city: "Busan", country: "KR" },
  { iata: "CAN", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "CN" },
  { iata: "SZX", name: "Shenzhen Bao'an International", city: "Shenzhen", country: "CN" },
  { iata: "CTU", name: "Chengdu Shuangliu International", city: "Chengdu", country: "CN" },
  { iata: "TPE", name: "Taiwan Taoyuan International", city: "Taipei", country: "TW" },
  { iata: "DPS", name: "Ngurah Rai International", city: "Denpasar", country: "ID" },
  { iata: "HKT", name: "Phuket International", city: "Phuket", country: "TH" },
  { iata: "CNX", name: "Chiang Mai International", city: "Chiang Mai", country: "TH" },
  { iata: "PEN", name: "Penang International", city: "Penang", country: "MY" },
  { iata: "CEB", name: "Mactan-Cebu International", city: "Cebu", country: "PH" },
  { iata: "DAD", name: "Da Nang International", city: "Da Nang", country: "VN" },
  { iata: "AMD", name: "Sardar Vallabhbhai Patel International", city: "Ahmedabad", country: "IN" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose International", city: "Kolkata", country: "IN" },
  { iata: "PNQ", name: "Pune", city: "Pune", country: "IN" },
  { iata: "ADL", name: "Adelaide", city: "Adelaide", country: "AU" },
  { iata: "OOL", name: "Gold Coast", city: "Gold Coast", country: "AU" },
  { iata: "CHC", name: "Christchurch", city: "Christchurch", country: "NZ" },

  // Canada
  { iata: "YYZ", name: "Toronto Pearson International", city: "Toronto", country: "CA" },
  { iata: "YUL", name: "Montreal-Trudeau International", city: "Montreal", country: "CA" },
  { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "CA" },
  { iata: "YYC", name: "Calgary International", city: "Calgary", country: "CA" },
  { iata: "YOW", name: "Ottawa Macdonald-Cartier", city: "Ottawa", country: "CA" },
  { iata: "YEG", name: "Edmonton International", city: "Edmonton", country: "CA" },
  { iata: "YWG", name: "Winnipeg James Armstrong Richardson International", city: "Winnipeg", country: "CA" },
  { iata: "YHZ", name: "Halifax Stanfield International", city: "Halifax", country: "CA" },
  { iata: "YQB", name: "Quebec City Jean Lesage International", city: "Quebec City", country: "CA" },

  // LatAm
  { iata: "GRU", name: "Sao Paulo/Guarulhos International", city: "Sao Paulo", country: "BR" },
  { iata: "GIG", name: "Rio de Janeiro/Galeao", city: "Rio de Janeiro", country: "BR" },
  { iata: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "AR" },
  { iata: "SCL", name: "Arturo Merino Benitez", city: "Santiago", country: "CL" },
  { iata: "BOG", name: "El Dorado International", city: "Bogota", country: "CO" },
  { iata: "MEX", name: "Benito Juarez International", city: "Mexico City", country: "MX" },
  { iata: "CUN", name: "Cancun International", city: "Cancun", country: "MX" },
  { iata: "LIM", name: "Jorge Chavez International", city: "Lima", country: "PE" },
  { iata: "PTY", name: "Tocumen International", city: "Panama City", country: "PA" },
  { iata: "SDQ", name: "Las Americas International", city: "Santo Domingo", country: "DO" },
  { iata: "SJU", name: "Luis Munoz Marin International", city: "San Juan", country: "PR" },
  { iata: "PUJ", name: "Punta Cana International", city: "Punta Cana", country: "DO" },
  { iata: "KIN", name: "Norman Manley International", city: "Kingston", country: "JM" },
  { iata: "GDL", name: "Miguel Hidalgo y Costilla Guadalajara International", city: "Guadalajara", country: "MX" },
  { iata: "MTY", name: "Monterrey International", city: "Monterrey", country: "MX" },
  { iata: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "EC" },
  { iata: "GYE", name: "Jose Joaquin de Olmedo International", city: "Guayaquil", country: "EC" },
  { iata: "MDE", name: "Jose Maria Cordova International", city: "Medellin", country: "CO" },
  { iata: "CLO", name: "Alfonso Bonilla Aragon International", city: "Cali", country: "CO" },
  { iata: "VVI", name: "Viru Viru International", city: "Santa Cruz", country: "BO" },
  { iata: "ASU", name: "Silvio Pettirossi International", city: "Asuncion", country: "PY" },
  { iata: "MVD", name: "Carrasco International", city: "Montevideo", country: "UY" },
  { iata: "POA", name: "Salgado Filho International", city: "Porto Alegre", country: "BR" },
  { iata: "BSB", name: "Brasilia International", city: "Brasilia", country: "BR" },

  // Africa
  { iata: "CAI", name: "Cairo International", city: "Cairo", country: "EG" },
  { iata: "CPT", name: "Cape Town International", city: "Cape Town", country: "ZA" },
  { iata: "JNB", name: "O.R. Tambo International", city: "Johannesburg", country: "ZA" },
  { iata: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "KE" },
  { iata: "LOS", name: "Murtala Muhammed International", city: "Lagos", country: "NG" },
  { iata: "ADD", name: "Bole International", city: "Addis Ababa", country: "ET" },
  { iata: "CMN", name: "Mohammed V International", city: "Casablanca", country: "MA" },
  { iata: "RAK", name: "Marrakesh Menara", city: "Marrakesh", country: "MA" },
  { iata: "TUN", name: "Tunis-Carthage International", city: "Tunis", country: "TN" },
  { iata: "ALG", name: "Houari Boumediene", city: "Algiers", country: "DZ" },
  { iata: "ACC", name: "Kotoka International", city: "Accra", country: "GH" },
  { iata: "DSS", name: "Blaise Diagne International", city: "Dakar", country: "SN" },
  { iata: "ABJ", name: "Felix-Houphouet-Boigny International", city: "Abidjan", country: "CI" },
  { iata: "DAR", name: "Julius Nyerere International", city: "Dar es Salaam", country: "TZ" },
  { iata: "EBB", name: "Entebbe International", city: "Entebbe", country: "UG" },
  { iata: "KGL", name: "Kigali International", city: "Kigali", country: "RW" },
  { iata: "LUN", name: "Kenneth Kaunda International", city: "Lusaka", country: "ZM" },
  { iata: "HRE", name: "Robert Gabriel Mugabe International", city: "Harare", country: "ZW" },
  { iata: "MPM", name: "Maputo International", city: "Maputo", country: "MZ" },
  { iata: "MRU", name: "Sir Seewoosagur Ramgoolam International", city: "Mauritius", country: "MU" },
];
